import { App } from "vue";

import TMenu from "@/app/components/Menu.vue";
import TCard from "@/app/components/Card.vue";
import TAlert from "@/app/components/Alert.vue";
import TButton from "@/app/components/Button.vue";
import TLabel from "@/app/components/Label.vue";
import TCollapse from "@/app/components/Collapse.vue";
import TCountTo from "@/app/components/CountTo.vue";
import TNotification from "@/app/components/Notification.vue";
import TModal from "@/app/components/Modal.vue";
import TProgressBar from "@/app/components/ProgressBar.vue";
import TPagination from "@/app/components/Pagination.vue";
import TTextarea from "@/app/components/formFields/Textarea.vue";
import TInputRange from "@/app/components/formFields/InputRange.vue";
import TValidationInputField from "@/app/components/formFields/ValidationInputField.vue";
import TSelect from "@/app/components/formFields/Select.vue";
import TCheckbox from "@/app/components/formFields/Checkbox.vue";
import TRadio from "@/app/components/formFields/Radio.vue";
import TSwitch from "@/app/components/formFields/Switch.vue";
import TFileUploader from "@/app/components/FileUploader.vue";
import TColorPicker from "@/app/components/ColorPicker.vue";
import TMultiSelect from "@/app/components/MultiSelect.vue";
import NumberInputSpinner from "@/app/components/NumberInputSpinner.vue";

export const initGlobalComponents = (app: App) => {
  app.component("TMenu", TMenu);
  app.component("TCard", TCard);
  app.component("TAlert", TAlert);
  app.component("TButton", TButton);
  app.component("TLabel", TLabel);
  app.component("TCollapse", TCollapse);
  app.component("TCountTo", TCountTo);
  app.component("TNotification", TNotification);
  app.component("TModal", TModal);
  app.component("TProgressBar", TProgressBar);
  app.component("TPagination", TPagination);
  app.component("TTextarea", TTextarea);
  app.component("TInputRange", TInputRange);
  app.component("TValidationInputField", TValidationInputField);
  app.component("TSelect", TSelect);
  app.component("TCheckbox", TCheckbox);
  app.component("TRadio", TRadio);
  app.component("TSwitch", TSwitch);
  app.component("TFileUploader", TFileUploader);
  app.component("TColorPicker", TColorPicker);
  app.component("TMultiSelect", TMultiSelect);
  app.component("TNumberInputSpinner", NumberInputSpinner);
};
